### PR TITLE
293-rename-datasafe-business-integration-test-files-for-clear-separation

### LINKED ISSUE #293: Rename datasafe-business Integration Test Files for Clear Separation
## Description
Identify integration test files within the datasafe-business subproject and rename them from the "Test" convention to follow the "IT" convention. This will establish a clear naming convention that distinguishes integration tests from unit tests.

## Definition of Done
In order to verify work is done:
- [x] Checkout the branch
- [x] Run the whole project with ```./mvnw clean verify -DskipTests```
- [x] Change to the project: ```cd datasafe-business/```
- [x] Run the module without skipTests ```../mvnw clean verify```. Check accurate number of tests is run
- [x] Run the module without skipTests ```../mvnw clean verify -PIT```. Check accurate number of tests is run

### PR DESCRIPTION
**Pull request by hanswizzy**

### CODE REVIEW

**Review by francis-pouatcha — COMMENTED** [review]
This class need to be renamed to SchemaDelegationIT as it uses testcontainers.

**Review by francis-pouatcha — COMMENTED** [review]
Class name and File name have to match.

**Review by francis-pouatcha — CHANGES_REQUESTED** [review]
Fix the class name

**Comment by hanswizzy** [comment]
> Class name and File name have to match.

okay sir thanks for the correction, working on it!

**Review by francis-pouatcha — APPROVED** [review]

**Pull request merged**
