### PR TITLE
185 more restrictive api for string arguments

### LINKED ISSUE #185: More restrictive API for String arguments
Currently some String based constructors, factory methods that are intended for internal use (i.e. Uri, BasePrivateResource.forPrivate ...) are not safe to use with non-url safe Strings. While it does not affect global usage as *Request api can accept any type of String, it is better to hide those String (Uri, BasePrivateResource.for..) constructors as implementation detail if needed and expose url-safe variants.

### PR DESCRIPTION
**Pull request by forkimenjeckayang**
- Modified some REST APIs in datasafe-rest-impl to enhance security with input / parameter validation

### CODE REVIEW

**Comment by max402** [comment]
It looks like original issue was fixed long time ago. URI was replaced with url-safe Uri wrapper class. The TODO in [BasePrivateResource](https://github.com/adorsys/datasafe/blob/c456aca1ca00874aed8cc147d0d6fb8bea778472/datasafe-types-api/src/main/java/de/adorsys/datasafe/types/api/resource/BasePrivateResource.java#L30) can be removed.

**Comment by forkimenjeckayang** [comment]
Noted Sir @max402 , i noticed too that's why there was little or nothing to do with the rest apis in datasafe-rest-impl. And by removing the TODO in  [BasePrivateResource](https://github.com/adorsys/datasafe/blob/c456aca1ca00874aed8cc147d0d6fb8bea778472/datasafe-types-api/src/main/java/de/adorsys/datasafe/types/api/resource/BasePrivateResource.java#L30) you mean everything from line 30 and below or just the 1 arg constructor ?

**Comment by max402** [comment]
@forkimenjeckayang No, I mean remove only the TODO comment line

**Comment by forkimenjeckayang** [comment]
Oh okay , just from doing that.

**Review by max402 — APPROVED** [review]

**Comment by max402** [comment]
@forkimenjeckayang please rebase you branch on top of current develop

**Comment by forkimenjeckayang** [comment]
OK @max402 , i have done that

**Comment by forkimenjeckayang** [comment]
Hello @max402  Should i go ahead and merge then close or you will do it

**Pull request merged**
